# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:zyjSE49WMdMVeVqjgEhYHupHafeTUuzuPKXplrZ8RcDaIvnNzPGUB6E+XOiNkPcPk+OrgTZIEDMukKzJowiNukNFOCgR29wivN+gi0kn5liReA5WEcjLloXu6rLTgCF77baYlRLlQqzRFuq5+fbUkHg7m4nCJHG18CPG4y9nJ/dE2wFhgYenqtJOUhhb8QxprIIusstZuN4E07YwG6LaXodCvJm1QS8kmnrqu+8aI+LlIZFIeA==,iv:68G6P025XH+Wx5px2bDhTWiwlO8Rc2KJ3KlfdCR1kDw=,tag:2oUhJrTwRFD5i8vOEp9Atg==,type:str]
sops:
  age:
    - recipient: age1h4q96yr98s9zusly004v3g39m6l6daplnmse7k2jykzwa806hfxqlrpgxr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdDUrUkRaazJNZW9rMXBF
        cWg2YlZYZm9OVVhXK2FkMEFjRGZDdFIrZHlFCkxibm9HTGNmUkNreEFzTys0MDBw
        Vm55bmZPcGNDdlkvamtIbHBHd0ZBNGcKLS0tIDhZM2pHcmt3NVU1TnZ5bEI3RU9L
        NGpaTHI2dXJ1MHpaRTM5YkRiVUpZSFkKpCj42ykzr0KiR1nI4grgATKhRXji87DQ
        A4BlMSyOpeAFawWQUr407yJ7ndvx0UilegsshfLyi2mI6XJK/rtz2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-08T13:36:36Z"
  mac: ENC[AES256_GCM,data:CBmDlEfINNAPZAJRnqeoeFytDpGp53vi/dtmrbIlzbquiFTgjqHNKgUUrk1UUleTZm5DMVbVFzv2VsP75faaxQMeOpt6DY3XnuOnBVKmRjCfd5a0m67FfFrWVm3gLk+Q/btdm5CQ0ZX+6jXxSxeTsBaMPJFKWLSgUyOjv37OC6U=,iv:buuL5tRJ9IbJtPn0RsDDRhRhfqaMk4x1TVlNm3D7Il8=,tag:3wBiDyq1YhOyAOVeG8jDiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.1
